# -*- coding: utf-8 -*-
"""translation_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S8tI8BHKB1AfExz3Tnu8pPLVWpt2YCYt
"""

# install googletrans using pip
!pip install googletrans

!pip3 uninstall googletrans
!pip3 install googletrans==3.1.0a0

# Importing the necessary libraries
import pandas as pd
import googletrans
from googletrans import Translator

# Reading and storing the CSV file as a dataframe
df = pd.read_csv("/your_recommendation.csv")
df.head(10)

source_lan = "en"  #en is the code for Hindi Language
translated_to= "te" #hi is the code for Hindi Language

translator = Translator()
translations = {}
for column in df.columns:
    # Unique elements of the column
    unique_elements = df[column].unique()
    for element in unique_elements:
        # Adding all the translations to a dictionary (translations)
        translations[element] = translator.translate(element, src=source_lan, dest = translated_to).text
translations

# Replacing all the translated words from the dictionary to the original dataframe
df.replace(translations, inplace = True)
df.head(10)







